RU = {
"Brand relaunch · proposal":"Перезапуск бренда · предложение",
"Tallinn feast pies":"Таллинские праздничные пироги",
"How to bring handmade pies to many more people: a new identity, new formats and new sales channels.":"Как донести пироги ручной работы до гораздо большего числа людей: новый образ, новые форматы и новые каналы продаж.",
"October 2026":"Октябрь 2026",
"Pirogoff pie box":"Коробка с пирогом Pirogoff",
"Pirogoff today":"Pirogoff сегодня",
"Pies people love.":"Пироги, которые любят.",
"Now it is time to be found.":"Пора, чтобы их нашли.",
"Facebook reviews recommend it – “like grandma made”":"отзывов на Facebook рекомендуют – «как у бабушки»",
"handmade pies, baked daily in Tiskre":"пирогов ручной работы, каждый день из пекарни в Тискре",
"counters in Rimi and Prisma hypermarkets + online shop and Wolt":"прилавка в гипермаркетах Rimi и Prisma + интернет-магазин и Wolt",
"your last Instagram post – time to start again":"последний пост в Instagram – пора начать снова",
"Pirogoff · Tallinn feast pies":"Pirogoff · Таллинские праздничные пироги",
"Chicken and porcini pie":"Пирог с курицей и белыми грибами",
"Revenue 2021–2025, €":"Выручка 2021–2025, €",
"2022 proved it: the demand is there.":"2022 год доказал: спрос есть.",
"With one format and no marketing, Pirogoff reached €168,000 in 2022. Today’s level (€132,000) shows how much room there is to grow.":"С одним форматом и без маркетинга Pirogoff достиг 168 000 € в 2022 году. Сегодняшний уровень (132 000 €) показывает, сколько ещё места для роста.",
"Source: Estonian business register, annual reports":"Источник: коммерческий регистр Эстонии, годовые отчёты",
"Where the growth is":"Где рост",
"Every channel is an opportunity today.":"Каждый канал сегодня – это возможность.",
"Channel":"Канал","Today":"Сегодня","Opportunity":"Возможность",
"183 · last post 2023":"183 · последний пост 2023",
"3 video formats, 3–4 posts a week":"3 видеоформата, 3–4 поста в неделю",
"0 reviews":"0 отзывов",
"A profile per counter + review card in the box":"Профиль для каждого прилавка + карточка с просьбой об отзыве в коробке",
"Wolt without ratings, no Bolt":"Wolt без оценок, Bolt нет",
"Photos, ratings, switch on Bolt Food":"Фото, оценки, подключить Bolt Food",
"Website":"Сайт",
"#1 for “pirukad Tallinn”":"1-е место по «pirukad Tallinn»",
"English + “order” and “delivery” searches":"Английская версия + запросы «заказать» и «доставка»",
"none yet":"пока нет",
"Cafés and supermarkets – the biggest growth source":"Кафе и супермаркеты – главный источник роста",
"Market and audience":"Рынок и аудитория",
"A big city, three audiences.":"Большой город, три аудитории.",
"residents in Tallinn":"жителей Таллина",
"3,42 mln":"3,42 млн",
"foreign visitors a year":"иностранных туристов в год",
"average gross wage, Harju":"средняя зарплата брутто, Харьюмаа",
"Regulars":"Постоянные клиенты",
"Russian-speaking locals (~34%) who know the pirog.":"Русскоязычные жители (~34%), которые знают пирог.",
"Estonians":"Эстонцы",
"The pirukas is Estonian too – Estonian first.":"Pirukas – это и эстонская традиция. Эстонский язык – на первом месте.",
"Tourists":"Туристы",
"A local taste and a beautiful box to take home.":"Местный вкус и красивая коробка с собой.",
"Competition":"Конкуренция",
"Demand is proven. The space is free.":"Спрос доказан. Ниша свободна.",
"Nikolay · same product, €30–38/kg":"Nikolay · тот же продукт, 30–38 €/кг",
"ratings on Bolt Food":"оценок в Bolt Food",
"reviews on Google":"отзывов в Google",
"Company":"Компания","Revenue · focus":"Выручка · фокус",
"106,8 mln € · industrial":"106,8 млн € · промышленное производство",
"29,9 mln € · bread, retail":"29,9 млн € · хлеб, розница",
"3,55 mln € · 9 cafés":"3,55 млн € · 9 кафе",
"homemade pies to order":"домашние пироги на заказ",
"Pirogoff sits at €21–37/kg – the same range. Nobody yet owns “handmade feast pie in every format”.":"Pirogoff стоит 21–37 €/кг – в том же диапазоне. Позицию «праздничный пирог ручной работы в любом формате» пока никто не занял.",
"Opportunities":"Возможности",
"Growth comes from B2B and new formats.":"Рост – за счёт B2B и новых форматов.",
"Cafés and supermarkets":"Кафе и супермаркеты",
"Slices, GO and KLASSIK on the local producers’ shelf.":"Куски, GO и KLASSIK на полке местных производителей.",
"Frozen range":"Замороженная линейка",
"AIR and KLASSIK: supermarket freezer and Wolt Market.":"AIR и KLASSIK: морозильник супермаркета и Wolt Market.",
"Gift box":"Подарочная коробка",
"For tourists: port and airport, 11.5 M passengers.":"Для туристов: порт и аэропорт, 11,5 млн пассажиров.",
"Holiday range":"Праздничная линейка",
"Christmas, Easter, Midsummer – pre-orders.":"Рождество, Пасха, Яанипяэв – предзаказы.",
"Pie of the week":"Пирог недели",
"Subscription: a new flavour home every Friday.":"Подписка: каждую пятницу новый вкус с доставкой домой.",
"Finland and the Baltics":"Финляндия и Балтия",
"“Northern Feast Pies” as the next step.":"«Northern Feast Pies» как следующий шаг.",
"Campaign":"Кампания",
"Just like when you were little.":"Как в детстве.",
"The taste that brings you home.":"Вкус, который возвращает домой.",
"The same flavours that were on grandma’s table. Every celebration, every family gathering, every tired evening – the pie is a tradition that makes you feel at home.":"Те же вкусы, что были на бабушкином столе. Каждый праздник, каждая семейная встреча, каждый усталый вечер – пирог как традиция, с которой ты дома.",
"Pie in its box on a linen cloth":"Пирог в коробке на льняной скатерти",
"Campaign · three moments":"Кампания · три момента",
"A pie should be a tradition.":"Пирог должен стать традицией.",
"The celebration":"Праздник",
"Every party has a pie.":"На каждом празднике – пирог.",
"Birthdays, Christmas, Midsummer – Pirogoff is on the table, as always.":"Дни рождения, Рождество, Яанипяэв – Pirogoff на столе, как всегда.",
"The family":"Семья",
"Every family gathering.":"Каждая семейная встреча.",
"The same taste as on grandma’s table. Now on yours.":"Тот же вкус, что на бабушкином столе. Теперь – на вашем.",
"The evening":"Вечер",
"Tired? A pie is waiting.":"Устал? Пирог ждёт.",
"Don’t know what to eat? A few minutes and you feel at home and loved.":"Не знаешь, что поесть? Несколько минут – и ты дома, тебя любят.",
"Campaign · where it lives":"Кампания · где она живёт",
"One story, at every touchpoint.":"Одна история – в каждой точке контакта.",
"Inside the lid":"Внутри крышки",
"“Welcome home.” + a card “Whose table is this?” – share your feast table.":"«Добро пожаловать домой.» + карточка «Чей это стол?» – поделитесь своим праздничным столом.",
"Trams and bus stops":"Трамваи и остановки",
"Evening poster: “Tired? A pie is waiting.”":"Вечерний плакат: «Устал? Пирог ждёт.»",
"Social and Wolt":"Соцсети и Wolt",
"Story series on grandparents and feast tables, a 6 pm Wolt offer.":"Серия историй о бабушках, дедушках и праздничных столах, предложение в Wolt в 18:00.",
"Carrot pie in its box":"Морковный пирог в коробке",
"Nordic":"Северный стиль",
"Brand identity":"Айдентика бренда",
"Warm, crafted, Nordic.":"Тёплый, ремесленный, северный.",
"Oat cream":"Овсяный крем","Rye brown":"Ржаной коричневый","Cornflower":"Василёк","Kraft":"Крафт",
"Logo:":"Логотип:",
"soft serif wordmark “Pirogoff” with a rye sprig – bread, field, craft.":"мягкий шрифт с засечками «Pirogoff» и колос ржи – хлеб, поле, ремесло.",
"Pattern:":"Узор:",
"one woven folk band – Nordic, not tied to one nation.":"одна тканая народная полоса – северная, не привязанная к одному народу.",
"Material:":"Материал:",
"matte board, round window, string. No plastic lamination (EU PPWR).":"матовый картон, круглое окно, бечёвка. Без пластиковой ламинации (EU PPWR).",
"Strawberry and ricotta pack":"Упаковка с клубникой и рикоттой",
"Colour code":"Цветовой код",
"Every flavour has its colour – recognised in a second.":"У каждого вкуса свой цвет – узнаётся за секунду.",
"Number, name and colour repeat on the lid, the sides, on Wolt and on the counter menu. Regulars simply order “number 02”.":"Номер, название и цвет повторяются на крышке, на боках, в Wolt и в меню прилавка. Постоянные клиенты просто заказывают «номер 02».",
"Packaging · the collection":"Упаковка · коллекция",
"One box, many flavours.":"Одна коробка, много вкусов.",
"Packaging · on the shelf":"Упаковка · на полке",
"A column of colour you can read from afar.":"Цветная колонна, которую видно издалека.",
"Pirogoff boxes on a store shelf":"Коробки Pirogoff на полке магазина",
"New formats":"Новые форматы",
"Small, medium, large – a pie for every moment.":"Маленький, средний, большой – пирог на каждый момент.",
"GO, AIR and KLASSIK formats":"Форматы GO, AIR и KLASSIK",
"Format 1 / 4":"Формат 1 / 4","Format 2 / 4":"Формат 2 / 4","Format 3 / 4":"Формат 3 / 4","Format 4 / 4":"Формат 4 / 4",
"A pie that fits in your hand.":"Пирог, который помещается в руке.",
"For whom":"Для кого","Where":"Где","Why":"Почему",
"Students, people on the way to work, grandma and grandchild on a walk.":"Студенты, люди по дороге на работу, бабушка с внуком на прогулке.",
"Existing counters, cafés, Wolt and Bolt Food.":"Существующие прилавки, кафе, Wolt и Bolt Food.",
"A small purchase brings new customers who would not buy a whole pie.":"Небольшая покупка приводит новых клиентов, которые не купили бы целый пирог.",
"Try it before you buy a whole one.":"Попробуй, прежде чем купить целый.",
"slice&nbsp;":"кусок&nbsp;",
"The café guest who wants something savoury with their coffee.":"Гость кафе, которому хочется чего-то солёного к кофе.",
"Cafés and café chains, the supermarket ready-food shelf.":"Кафе и сети кафе, полка готовой еды в супермаркете.",
"The easiest B2B product: boxed, labelled, fresh every day.":"Самый простой B2B-продукт: в коробке, с этикеткой, свежий каждый день.",
"From the freezer to dinner.":"Из морозилки – к ужину.",
"350 g · frozen · for the air fryer":"350 г · замороженный · для аэрогриля",
"The tired evening when you don’t know what to eat – a warm pie in minutes.":"Усталый вечер, когда не знаешь, что поесть, – тёплый пирог за несколько минут.",
"The supermarket freezer and Wolt Market.":"Морозильник супермаркета и Wolt Market.",
"Long shelf life, less waste, weekly delivery.":"Долгий срок хранения, меньше списаний, поставка раз в неделю.",
"The feast pie – finish baking at home.":"Праздничный пирог – допеки дома.",
"1 kg · fresh or frozen":"1 кг · свежий или замороженный",
"Holidays, birthdays, family gatherings.":"Праздники, дни рождения, семейные встречи.",
"Online shop, counters, supermarket freezer.":"Интернет-магазин, прилавки, морозильник супермаркета.",
"Today’s core product in a new life: from the oven to the table,":"Сегодняшний главный продукт в новой жизни: из духовки на стол,",
"&nbsp;warm and fragrant.":"&nbsp;тёплый и ароматный.",
"Social · every channel":"Соцсети · все каналы",
"We activate every page – each with its own job.":"Запускаем все страницы – у каждой своя задача.",
"Business account, Reels, stories. ET + RU + EN.":"Бизнес-аккаунт, Reels, сторис. ET + RU + EN.",
"3–4 posts a week":"3–4 поста в неделю",
"New account: kitchen POV, “Pie on test”.":"Новый аккаунт: POV из кухни, «Пирог на тесте».",
"3 videos a week":"3 видео в неделю",
"Community, events, reviews, Russian-speaking audience.":"Сообщество, события, отзывы, русскоязычная аудитория.",
"2 posts a week":"2 поста в неделю",
"4 profiles – every counter: photos, hours, reviews.":"4 профиля – каждый прилавок: фото, часы работы, отзывы.",
"Reply to every review":"Ответ на каждый отзыв",
"Photos, colour-coded menu, morning opening.":"Фото, меню с цветовым кодом, работа с утра.",
"Weekly offer":"Предложение каждую неделю",
"The same videos in one more place – no extra work.":"Те же видео ещё в одном месте – без лишней работы.",
"Repurposed":"Повторное использование",
"Formats that build connection":"Форматы, которые создают связь",
"People don’t follow a bakery. They follow stories.":"Люди подписываются не на пекарню. Они подписываются на истории.",
"“Grandma’s recipe”":"«Бабушкин рецепт»",
"Grandparents share their pie memories on camera.":"Бабушки и дедушки рассказывают на камеру свои воспоминания о пирогах.",
"“Whose table is this?”":"«Чей это стол?»",
"Customers send feast-table photos – the best wins a month of pies.":"Клиенты присылают фото праздничного стола – лучший получает пироги на месяц.",
"“The evening rescue”":"«Вечернее спасение»",
"6 pm: tired? AIR into the fryer, dinner is ready in minutes.":"18:00: устал? AIR в аэрогриль – ужин готов за несколько минут.",
"“POV: a pie is born”":"«POV: рождается пирог»",
"5 am in the Tiskre kitchen – dough, filling, braid, oven.":"5 утра на кухне в Тискре – тесто, начинка, косичка, печь.",
"“Pie on test”":"«Пирог на тесте»",
"Honest reviews by local creators and customers.":"Честные обзоры от местных блогеров и клиентов.",
"“Holiday calendar”":"«Календарь праздников»",
"A pie for every holiday – a pre-order countdown.":"Пирог к каждому празднику – обратный отсчёт до предзаказа.",
"Pirogoff in every café and supermarket.":"Pirogoff в каждом кафе и супермаркете.",
"Buyer":"Покупатель","What we offer":"Что предлагаем","Delivery":"Поставка",
"Cafés and café chains":"Кафе и сети кафе",
"Savoury TÜKK slices and GO":"Солёные куски TÜKK и GO",
"Daily, chilled":"Ежедневно, охлаждённые",
"Supermarkets (Selver, Coop, Rimi, Prisma)":"Супермаркеты (Selver, Coop, Rimi, Prisma)",
"Local producers’ shelf: slices, KLASSIK, AIR":"Полка местных производителей: куски, KLASSIK, AIR",
"2–3× a week / frozen":"2–3 раза в неделю / замороженные",
"AIR and KLASSIK frozen":"AIR и KLASSIK замороженные",
"Weekly":"Раз в неделю",
"lab analysis per recipe (LABRIS)":"лабораторный анализ на рецепт (LABRIS)",
"2–4 days":"2–4 дня",
"shelf life chilled – or frozen":"срок хранения в охлаждённом виде – или заморозка",
"Estonian labels and barcode":"этикетка на эстонском и штрихкод",
"Roadmap":"Дорожная карта",
"We start from the existing points.":"Начинаем с существующих точек.",
"0–30 days":"0–30 дней",
"Tidy up":"Навести порядок",
"Google profiles, Bolt Food, Wolt, every social page, website.":"Профили Google, Bolt Food, Wolt, все страницы в соцсетях, сайт.",
"1–3 months":"1–3 месяца",
"Test":"Тест",
"Slices and GO at the existing counters. Balti Jaama Turg analysis.":"Куски и GO на существующих прилавках. Анализ Balti Jaama Turg.",
"3–6 months":"3–6 месяцев",
"Cafés and supermarkets, new packaging, lab and labels.":"Кафе и супермаркеты, новая упаковка, лаборатория и этикетки.",
"6–12 months":"6–12 месяцев",
"Grow":"Рост",
"Frozen range. A central mini-shop only if B2B needs it.":"Замороженная линейка. Мини-магазин в центре – только если он нужен для B2B.",
"If B2B works, an expensive central location is not needed: less rent, more money for marketing and production.":"Если B2B работает, дорогое место в центре не нужно: меньше аренды, больше денег на маркетинг и производство.",
"12-month goals":"Цели на 12 месяцев",
"Where we get to in a year.":"Куда мы придём за год.",
"revenue – back to the 2022 level and beyond":"выручка – возврат к уровню 2022 года и выше",
"ratings on Wolt and Bolt Food":"оценок в Wolt и Bolt Food",
"regular B2B clients":"постоянных B2B-клиентов",
"active social channels":"активных каналов в соцсетях",
"Grants":"Гранты",
"EIS development voucher up to €35,000":"Ваучер развития EIS до 35 000 €",
"PRIA food industry 15–50%":"PRIA для пищевой промышленности 15–50%",
"Tallinn digital grant up to €6,000/yr":"Цифровой грант Таллина до 6 000 € в год",
"Next steps":"Следующие шаги",
"Let’s make every pie a feast.":"Сделаем каждый пирог праздником.",
"Meeting and feedback on this proposal":"Встреча и обратная связь по предложению",
"Sales data by channel and costs":"Данные о продажах по каналам и затраты",
"Kick-off: the first 30 days":"Старт: первые 30 дней",
"Pirogoff pie in its box":"Пирог Pirogoff в коробке",
"Pirogoff · Tallinn feast pies – proposal":"Pirogoff · Таллинские праздничные пироги – предложение",
"Opening and where we stand":"Вступление и текущая ситуация",
"Market, competition and opportunities":"Рынок, конкуренция и возможности",
"Campaign “Just like when you were little”":"Кампания «Как в детстве»",
"Brand, packaging and formats":"Бренд, упаковка и форматы",
"Social media and B2B":"Соцсети и B2B",
"Plan":"План",
"Savoury":"Солёный","Sweet":"Сладкий",
}
